### ISSUE TITLE
없는 메뉴 선택했을때 에러 처리하기

### ISSUE THREAD

**Issue by HDhye** [Heeheehye/miniproject#6]
![Image](https://user-images.githubusercontent.com/121746804/234511181-e031b8d8-17b9-4ddb-96c0-fcdfbe3c8c4d.png)

```
public drinks orderMenu(int selectMenu) {
		drinks bev = new drinks(); 
		for (int i = 0; i < init.getBev().length; i++) {
			if(init.getBev()[i].getNum() == selectMenu ) {
				System.out.println("선택 메뉴 : " + init.getBev()[i]);	
				bev = init.getBev()[i];
				break; 
			} else {
				System.out.println("선택한 메뉴는 없는 메뉴입니다.");
			}
		} return bev; 
	}
```

**Comment by heeyoonsz** [comment]
try catch로 해결해보시는건 어떠신가요

**Comment by daheeh** [comment]
> try catch로 해결해보시는건 어떠신가요

님의 의견에 동의합니다

**Comment by HDhye** [comment]
![Image](https://user-images.githubusercontent.com/121746804/234513655-096a9368-4ef9-4da1-b9fd-d1e9589af13e.png)


![Image](https://user-images.githubusercontent.com/121746804/234513762-c3208194-25df-4fe2-9e5a-0e16747bb916.png)


해결했습니다

**Comment by heeyoonsz** [comment]
해결하신거 축하드려요
